version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
        update-types:
          - minor
          - patch
      spring:
        patterns:
          - "org.springframework*"
          - "io.spring*"
        update-types:
          - minor
          - patch

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch