ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY curl_chrome120 /usr/local/bin/curl_chrome120
COPY curl-impersonate /usr/local/bin/curl-impersonate

RUN chmod +x /usr/local/bin/curl_chrome120 /usr/local/bin/curl-impersonate