on:
  push:
    branches-ignore:
      - main

name: Build and Test code

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb

      - name: Build and Test
        timeout-minutes: 25
        run: |
          ./gradlew build

      - name: Verify dependency locks are up to date
        run: |
          ./gradlew dependencies --write-locks
          git diff --exit-code -- gradle.lockfile
  build-native:
    runs-on: ubuntu-latest
    name: Build Native
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@0426e2e191540e8514dff98dc52a5f5146a2a276
        with:
          java-version: 25
          distribution: graalvm

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb

      - name: Compile Native Image
        run: |
          ./gradlew nativeCompile