on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        uses: fjogeleit/http-request-action@f98bb26551cd1af7d3eb2674578a80754ece88db
        with:
          url: 'https://api.shirtscanner.com/v1/providers'
